/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoordinacionRouteImport } from './routes/coordinacion'
import { Route as IngresoRouteImport } from './routes/ingreso'
import { Route as MonitorRouteImport } from './routes/monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinacionRoute = CoordinacionRouteImport.update({
  id: '/coordinacion',
  path: '/coordinacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordinacion': typeof CoordinacionRoute
  '/ingreso': typeof IngresoRoute
  '/monitor': typeof MonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordinacion': typeof CoordinacionRoute
  '/ingreso': typeof IngresoRoute
  '/monitor': typeof MonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordinacion': typeof CoordinacionRoute
  '/ingreso': typeof IngresoRoute
  '/monitor': typeof MonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coordinacion' | '/ingreso' | '/monitor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coordinacion' | '/ingreso' | '/monitor'
  id: '__root__' | '/' | '/coordinacion' | '/ingreso' | '/monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordinacionRoute: typeof CoordinacionRoute
  IngresoRoute: typeof IngresoRoute
  MonitorRoute: typeof MonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinacion': {
      id: '/coordinacion'
      path: '/coordinacion'
      fullPath: '/coordinacion'
      preLoaderRoute: typeof CoordinacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordinacionRoute: CoordinacionRoute,
  IngresoRoute: IngresoRoute,
  MonitorRoute: MonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
